# Generated by Django 4.0.1 on 2022-01-16 17:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtr5app', '0041_pushnotificationendpoint_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_lookingfor',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(choices=[(0, 'other'), (1, 'woman who likes men'), (2, 'woman who likes women'), (3, 'woman who likes diverse'), (4, 'man who likes women'), (5, 'man who likes men'), (6, 'man who likes diverse'), (7, 'diverse who likes women'), (8, 'diverse who likes men'), (9, 'diverse who likes diverse')], default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='host',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='was_visited', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='visited', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
