version: "3.7"

services:
  db:
    image: postgres
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis:
    image: "redis"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
      # >
      # sh -c "python manage.py makemigrations &&
      #        python manage.py migrate &&
      #        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - ISDEV=1
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
